
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WordSmithConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=WordSmith;Integrated Security=True;`
//     Schema:                 ``
//     Include Views:          `False`

using System;
using System.Collections.Generic;
using System.Linq;
using NPoco;

namespace WordSmith.Core.Models.Database {
	

    
	[TableName("tSentenceLog")]
			[PrimaryKey("Id")]
				[ExplicitColumns]
    public partial class SentenceLog {
			[Column] public int Id { get; set; }
	
			[Column] public string Sentence { get; set; }
	
			[Column] public DateTime LogDate { get; set; }
	
	}
    
	[TableName("tErrorLog")]
			[PrimaryKey("Id")]
				[ExplicitColumns]
    public partial class ErrorLog {
			[Column] public int Id { get; set; }
	
			[Column] public DateTime LogDate { get; set; }
	
			[Column] public string Message { get; set; }
	
			[Column] public string Stacktrace { get; set; }
	
			[Column] public string Server { get; set; }
	
	}
}


