CREATE TABLE [dbo].[tSentenceLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Sentence] [varchar](max) NOT NULL,
	[LogDate] [datetime] NOT NULL,
 CONSTRAINT [PK_tSentenceLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[tErrorLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LogDate] [datetime] NOT NULL,
	[Message] [varchar](max) NOT NULL,
	[Stacktrace] [varchar](max) NOT NULL,
	[Server] [varchar](150) NOT NULL,
 CONSTRAINT [PK_tErrorLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO



